
window.bl = window.bl || {};
window.bl.resources = {
    "_shared_resources": "../../shared-resources/",
    "fonts": "../../shared-resources/fonts/",
    "images": "../../shared-resources/images/",
    "images_clock": "../../shared-resources/images/clock/",
    "images_clock_am": "../../shared-resources/images/clock/AM.png",
    "images_clock_am_small": "../../shared-resources/images/clock/AM_Small.png",
    "images_clock_arrow_down": "../../shared-resources/images/clock/Arrow_Down.png",
    "images_clock_arrow_down_small": "../../shared-resources/images/clock/Arrow_Down_Small.png",
    "images_clock_arrow_up": "../../shared-resources/images/clock/Arrow_Up.png",
    "images_clock_arrow_up_small": "../../shared-resources/images/clock/Arrow_Up_Small.png",
    "images_clock_clock_cards": "../../shared-resources/images/clock/clock_cards/",
    "images_clock_clock_cards_clock_card_1": "../../shared-resources/images/clock/clock_cards/Clock_Card_1.png",
    "images_clock_clock_cards_clock_card_10": "../../shared-resources/images/clock/clock_cards/Clock_Card_10.png",
    "images_clock_clock_cards_clock_card_11": "../../shared-resources/images/clock/clock_cards/Clock_Card_11.png",
    "images_clock_clock_cards_clock_card_12": "../../shared-resources/images/clock/clock_cards/Clock_Card_12.png",
    "images_clock_clock_cards_clock_card_2": "../../shared-resources/images/clock/clock_cards/Clock_Card_2.png",
    "images_clock_clock_cards_clock_card_3": "../../shared-resources/images/clock/clock_cards/Clock_Card_3.png",
    "images_clock_clock_cards_clock_card_4": "../../shared-resources/images/clock/clock_cards/Clock_Card_4.png",
    "images_clock_clock_cards_clock_card_5": "../../shared-resources/images/clock/clock_cards/Clock_Card_5.png",
    "images_clock_clock_cards_clock_card_6": "../../shared-resources/images/clock/clock_cards/Clock_Card_6.png",
    "images_clock_clock_cards_clock_card_7": "../../shared-resources/images/clock/clock_cards/Clock_Card_7.png",
    "images_clock_clock_cards_clock_card_8": "../../shared-resources/images/clock/clock_cards/Clock_Card_8.png",
    "images_clock_clock_cards_clock_card_9": "../../shared-resources/images/clock/clock_cards/Clock_Card_9.png",
    "images_clock_clock_centre_pin": "../../shared-resources/images/clock/Clock_Centre_Pin.png",
    "images_clock_clock_face": "../../shared-resources/images/clock/Clock_Face.png",
    "images_clock_clock_numbers_3_6_9_12": "../../shared-resources/images/clock/Clock_Numbers_3-6-9-12.png",
    "images_clock_clock_numbers_all": "../../shared-resources/images/clock/Clock_Numbers_All.png",
    "images_clock_digital_bg": "../../shared-resources/images/clock/digital_bg.png",
    "images_clock_digital_bg_small": "../../shared-resources/images/clock/digital_bg_Small.png",
    "images_clock_digits": "../../shared-resources/images/clock/digits/",
    "images_clock_digits_0": "../../shared-resources/images/clock/digits/0.png",
    "images_clock_digits_0_small": "../../shared-resources/images/clock/digits/0_Small.png",
    "images_clock_digits_1": "../../shared-resources/images/clock/digits/1.png",
    "images_clock_digits_1_small": "../../shared-resources/images/clock/digits/1_Small.png",
    "images_clock_digits_2": "../../shared-resources/images/clock/digits/2.png",
    "images_clock_digits_2_small": "../../shared-resources/images/clock/digits/2_Small.png",
    "images_clock_digits_3": "../../shared-resources/images/clock/digits/3.png",
    "images_clock_digits_3_small": "../../shared-resources/images/clock/digits/3_Small.png",
    "images_clock_digits_4": "../../shared-resources/images/clock/digits/4.png",
    "images_clock_digits_4_small": "../../shared-resources/images/clock/digits/4_Small.png",
    "images_clock_digits_5": "../../shared-resources/images/clock/digits/5.png",
    "images_clock_digits_5_small": "../../shared-resources/images/clock/digits/5_Small.png",
    "images_clock_digits_6": "../../shared-resources/images/clock/digits/6.png",
    "images_clock_digits_6_small": "../../shared-resources/images/clock/digits/6_Small.png",
    "images_clock_digits_7": "../../shared-resources/images/clock/digits/7.png",
    "images_clock_digits_7_small": "../../shared-resources/images/clock/digits/7_Small.png",
    "images_clock_digits_8": "../../shared-resources/images/clock/digits/8.png",
    "images_clock_digits_8_small": "../../shared-resources/images/clock/digits/8_Small.png",
    "images_clock_digits_9": "../../shared-resources/images/clock/digits/9.png",
    "images_clock_digits_9_small": "../../shared-resources/images/clock/digits/9_Small.png",
    "images_clock_digits_colon": "../../shared-resources/images/clock/digits/colon.png",
    "images_clock_digits_colon_small": "../../shared-resources/images/clock/digits/colon_Small.png",
    "images_clock_hour_hand": "../../shared-resources/images/clock/Hour_hand.png",
    "images_clock_hour_hand_handle": "../../shared-resources/images/clock/Hour_hand_handle.png",
    "images_clock_minute_hand": "../../shared-resources/images/clock/Minute_hand.png",
    "images_clock_minute_hand_handle": "../../shared-resources/images/clock/Minute_hand_handle.png",
    "images_clock_options_close_button": "../../shared-resources/images/clock/Options_Close_button.png",
    "images_clock_options_digital_button_grey": "../../shared-resources/images/clock/Options_Digital_button_grey.png",
    "images_clock_options_digital_button_orange": "../../shared-resources/images/clock/Options_Digital_button_Orange.png",
    "images_clock_options_hour_button_grey": "../../shared-resources/images/clock/Options_Hour_button_grey.png",
    "images_clock_options_hour_button_orange": "../../shared-resources/images/clock/Options_Hour_button_Orange.png",
    "images_clock_options_minute_button_grey": "../../shared-resources/images/clock/Options_Minute_button_grey.png",
    "images_clock_options_minute_button_orange": "../../shared-resources/images/clock/Options_Minute_button_Orange.png",
    "images_clock_options_open_button": "../../shared-resources/images/clock/Options_Open_button.png",
    "images_clock_options_panel": "../../shared-resources/images/clock/Options_Panel.png",
    "images_clock_options_sentence_button_grey": "../../shared-resources/images/clock/Options_Sentence_button_grey.png",
    "images_clock_options_sentence_button_orange": "../../shared-resources/images/clock/Options_Sentence_button_Orange.png",
    "images_clock_options_words_button_grey": "../../shared-resources/images/clock/Options_Words_button_grey.png",
    "images_clock_options_words_button_orange": "../../shared-resources/images/clock/Options_Words_button_Orange.png",
    "images_clock_pm": "../../shared-resources/images/clock/PM.png",
    "images_clock_pm_small": "../../shared-resources/images/clock/PM_Small.png",
    "images_clock_preview": "../../shared-resources/images/clock/preview/",
    "images_clock_preview_clock_tool_analog": "../../shared-resources/images/clock/preview/Clock_Tool_analog.png",
    "images_clock_preview_clock_tool_both": "../../shared-resources/images/clock/preview/Clock_Tool_both.png",
    "images_clock_preview_clock_tool_digital": "../../shared-resources/images/clock/preview/Clock_Tool_digital.png",
    "images_clock_settings": "../../shared-resources/images/clock/settings/",
    "images_clock_settings_12hr_off": "../../shared-resources/images/clock/settings/12hr_Off.png",
    "images_clock_settings_12hr_on": "../../shared-resources/images/clock/settings/12hr_On.png",
    "images_clock_settings_24hr_off": "../../shared-resources/images/clock/settings/24hr_Off.png",
    "images_clock_settings_24hr_on": "../../shared-resources/images/clock/settings/24hr_On.png",
    "images_clock_settings_analog_button_off": "../../shared-resources/images/clock/settings/Analog_Button_Off.png",
    "images_clock_settings_analog_button_on": "../../shared-resources/images/clock/settings/Analog_Button_On.png",
    "images_clock_settings_analoganddigital_button_off": "../../shared-resources/images/clock/settings/AnalogAndDigital_Button_Off.png",
    "images_clock_settings_analoganddigital_button_on": "../../shared-resources/images/clock/settings/AnalogAndDigital_Button_On.png",
    "images_clock_settings_digital_button_off": "../../shared-resources/images/clock/settings/Digital_Button_Off.png",
    "images_clock_settings_digital_button_on": "../../shared-resources/images/clock/settings/Digital_Button_On.png",
    "images_clock_settings_free_form_bg": "../../shared-resources/images/clock/settings/Free_Form_BG.png",
    "images_clock_settings_free_form_closebutton": "../../shared-resources/images/clock/settings/Free_Form_CloseButton.png",
    "images_clock_settings_markers_off": "../../shared-resources/images/clock/settings/Markers_Off.png",
    "images_clock_settings_markers_on": "../../shared-resources/images/clock/settings/Markers_On.png",
    "images_clock_settings_numbers_off": "../../shared-resources/images/clock/settings/Numbers_Off.png",
    "images_clock_settings_numbers_on": "../../shared-resources/images/clock/settings/Numbers_On.png",
    "images_clock_settings_sentence_off": "../../shared-resources/images/clock/settings/Sentence_Off.png",
    "images_clock_settings_sentence_on": "../../shared-resources/images/clock/settings/Sentence_On.png",
    "images_clock_settings_settings_button": "../../shared-resources/images/clock/settings/Settings_button.png",
    "images_clock_settings_settings_button_base": "../../shared-resources/images/clock/settings/Settings_button_base.png",
    "images_clock_settings_words_off": "../../shared-resources/images/clock/settings/Words_Off.png",
    "images_clock_settings_words_on": "../../shared-resources/images/clock/settings/Words_On.png",
    "images_clock_title": "../../shared-resources/images/clock/Title.png",
    "images_closenormal": "../../shared-resources/images/CloseNormal.png",
    "images_deep_water_background": "../../shared-resources/images/deep_water_background.png",
    "images_geoboard": "../../shared-resources/images/geoboard/",
    "images_geoboard_addpinbutton": "../../shared-resources/images/geoboard/addPinButton.png",
    "images_geoboard_anglebackground": "../../shared-resources/images/geoboard/angleBackground.png",
    "images_geoboard_arrow_down_button": "../../shared-resources/images/geoboard/Arrow_down_button.png",
    "images_geoboard_arrow_up_button": "../../shared-resources/images/geoboard/Arrow_up_button.png",
    "images_geoboard_background": "../../shared-resources/images/geoboard/background.png",
    "images_geoboard_band_1_white": "../../shared-resources/images/geoboard/Band_1_white.png",
    "images_geoboard_band_button": "../../shared-resources/images/geoboard/Band_button.png",
    "images_geoboard_band_button_base": "../../shared-resources/images/geoboard/Band_button_base.png",
    "images_geoboard_band_circle": "../../shared-resources/images/geoboard/Band_Circle.png",
    "images_geoboard_bandbutton": "../../shared-resources/images/geoboard/bandButton.png",
    "images_geoboard_bandpart": "../../shared-resources/images/geoboard/bandPart.png",
    "images_geoboard_centrepinbutton": "../../shared-resources/images/geoboard/centrePinButton.png",
    "images_geoboard_centrepoint_button": "../../shared-resources/images/geoboard/CentrePoint_button.png",
    "images_geoboard_circlepin_button": "../../shared-resources/images/geoboard/CirclePin_button.png",
    "images_geoboard_circlepin_button_base": "../../shared-resources/images/geoboard/CirclePin_button_base.png",
    "images_geoboard_circularbutton": "../../shared-resources/images/geoboard/circularButton.png",
    "images_geoboard_colour_box_empty": "../../shared-resources/images/geoboard/colour_box_empty.png",
    "images_geoboard_colour_select": "../../shared-resources/images/geoboard/Colour_select.png",
    "images_geoboard_colour_selected": "../../shared-resources/images/geoboard/colour_selected.png",
    "images_geoboard_geoboard_title": "../../shared-resources/images/geoboard/Geoboard_title.png",
    "images_geoboard_hand": "../../shared-resources/images/geoboard/Hand.png",
    "images_geoboard_hand_up": "../../shared-resources/images/geoboard/hand_up.png",
    "images_geoboard_info_side_button": "../../shared-resources/images/geoboard/Info_Side_Button.png",
    "images_geoboard_info_side_button_highlight": "../../shared-resources/images/geoboard/Info_Side_Button_highlight.png",
    "images_geoboard_inspect_button": "../../shared-resources/images/geoboard/Inspect_button.png",
    "images_geoboard_isopin_button": "../../shared-resources/images/geoboard/IsoPin_button.png",
    "images_geoboard_isopin_button_base": "../../shared-resources/images/geoboard/IsoPin_button_base.png",
    "images_geoboard_label_panel": "../../shared-resources/images/geoboard/label_panel.png",
    "images_geoboard_minuspinbutton": "../../shared-resources/images/geoboard/minusPinButton.png",
    "images_geoboard_newbandbutton": "../../shared-resources/images/geoboard/newBandButton.png",
    "images_geoboard_number_box": "../../shared-resources/images/geoboard/Number_box.png",
    "images_geoboard_parallelsidearrow": "../../shared-resources/images/geoboard/parallelSideArrow.png",
    "images_geoboard_pin": "../../shared-resources/images/geoboard/pin.png",
    "images_geoboard_pin_white": "../../shared-resources/images/geoboard/Pin_white.png",
    "images_geoboard_pin_white_noshadow": "../../shared-resources/images/geoboard/Pin_white_noShadow.png",
    "images_geoboard_pinboardbackground": "../../shared-resources/images/geoboard/pinboardBackground.png",
    "images_geoboard_propertybackground": "../../shared-resources/images/geoboard/propertyBackground.png",
    "images_geoboard_removebandbutton": "../../shared-resources/images/geoboard/removeBandButton.png",
    "images_geoboard_rubberband_base": "../../shared-resources/images/geoboard/RubberBand_base.png",
    "images_geoboard_rubberband_icon": "../../shared-resources/images/geoboard/RubberBand_Icon.png",
    "images_geoboard_sameanglebutton": "../../shared-resources/images/geoboard/sameAngleButton.png",
    "images_geoboard_sameanglebuttonselected": "../../shared-resources/images/geoboard/sameAngleButtonSelected.png",
    "images_geoboard_samesidelengthbutton": "../../shared-resources/images/geoboard/sameSideLengthButton.png",
    "images_geoboard_samesidelengthbuttonselected": "../../shared-resources/images/geoboard/sameSideLengthButtonSelected.png",
    "images_geoboard_samesidelengthnotch": "../../shared-resources/images/geoboard/sameSideLengthNotch.png",
    "images_geoboard_showanglesbutton": "../../shared-resources/images/geoboard/showAnglesButton.png",
    "images_geoboard_showanglesbuttonselected": "../../shared-resources/images/geoboard/showAnglesButtonSelected.png",
    "images_geoboard_showparallelsidesbutton": "../../shared-resources/images/geoboard/showParallelSidesButton.png",
    "images_geoboard_showparallelsidesbuttonselected": "../../shared-resources/images/geoboard/showParallelSidesButtonSelected.png",
    "images_geoboard_showsidelengthsbutton": "../../shared-resources/images/geoboard/showSideLengthsButton.png",
    "images_geoboard_showsidelengthsbuttonselected": "../../shared-resources/images/geoboard/showSideLengthsButtonSelected.png",
    "images_geoboard_sidelabelbackground": "../../shared-resources/images/geoboard/sideLabelBackground.png",
    "images_geoboard_singlebandpart": "../../shared-resources/images/geoboard/singleBandPart.png",
    "images_geoboard_squarelatticebutton": "../../shared-resources/images/geoboard/squareLatticeButton.png",
    "images_geoboard_squarepin_button": "../../shared-resources/images/geoboard/SquarePin_button.png",
    "images_geoboard_squarepin_button_base": "../../shared-resources/images/geoboard/SquarePin_button_base.png",
    "images_geoboard_trash_button": "../../shared-resources/images/geoboard/trash_button.png",
    "images_geoboard_trash_button_base": "../../shared-resources/images/geoboard/trash_button_base.png",
    "images_geoboard_triangularlatticebutton": "../../shared-resources/images/geoboard/triangularLatticeButton.png",
    "images_geoboard_whitepin": "../../shared-resources/images/geoboard/whitePin.png",
    "images_object": "../../shared-resources/images/object.png",
    "images_sand_background": "../../shared-resources/images/sand_background.jpg",
    "images_sorting": "../../shared-resources/images/sorting/",
    "images_sorting_barchart_axis_x": "../../shared-resources/images/sorting/BarChart_Axis_X.png",
    "images_sorting_barchart_axis_y": "../../shared-resources/images/sorting/BarChart_Axis_Y.png",
    "images_sorting_bars": "../../shared-resources/images/sorting/Bars/",
    "images_sorting_bars_blue_bar_1": "../../shared-resources/images/sorting/Bars/Blue_Bar_1.png",
    "images_sorting_bars_blue_bar_2": "../../shared-resources/images/sorting/Bars/Blue_Bar_2.png",
    "images_sorting_bars_blue_bar_3": "../../shared-resources/images/sorting/Bars/Blue_Bar_3.png",
    "images_sorting_bars_blue_bar_4": "../../shared-resources/images/sorting/Bars/Blue_Bar_4.png",
    "images_sorting_bars_blue_bar_5": "../../shared-resources/images/sorting/Bars/Blue_Bar_5.png",
    "images_sorting_bars_green_bar_1": "../../shared-resources/images/sorting/Bars/Green_Bar_1.png",
    "images_sorting_bars_green_bar_2": "../../shared-resources/images/sorting/Bars/Green_Bar_2.png",
    "images_sorting_bars_green_bar_3": "../../shared-resources/images/sorting/Bars/Green_Bar_3.png",
    "images_sorting_bars_green_bar_4": "../../shared-resources/images/sorting/Bars/Green_Bar_4.png",
    "images_sorting_bars_green_bar_5": "../../shared-resources/images/sorting/Bars/Green_Bar_5.png",
    "images_sorting_bars_orange_bar_1": "../../shared-resources/images/sorting/Bars/Orange_Bar_1.png",
    "images_sorting_bars_orange_bar_2": "../../shared-resources/images/sorting/Bars/Orange_Bar_2.png",
    "images_sorting_bars_orange_bar_3": "../../shared-resources/images/sorting/Bars/Orange_Bar_3.png",
    "images_sorting_bars_orange_bar_4": "../../shared-resources/images/sorting/Bars/Orange_Bar_4.png",
    "images_sorting_bars_orange_bar_5": "../../shared-resources/images/sorting/Bars/Orange_Bar_5.png",
    "images_sorting_bars_pink_bar_1": "../../shared-resources/images/sorting/Bars/Pink_Bar_1.png",
    "images_sorting_bars_pink_bar_2": "../../shared-resources/images/sorting/Bars/Pink_Bar_2.png",
    "images_sorting_bars_pink_bar_3": "../../shared-resources/images/sorting/Bars/Pink_Bar_3.png",
    "images_sorting_bars_pink_bar_4": "../../shared-resources/images/sorting/Bars/Pink_Bar_4.png",
    "images_sorting_bars_pink_bar_5": "../../shared-resources/images/sorting/Bars/Pink_Bar_5.png",
    "images_sorting_bars_red_bar_1": "../../shared-resources/images/sorting/Bars/Red_Bar_1.png",
    "images_sorting_bars_red_bar_2": "../../shared-resources/images/sorting/Bars/Red_Bar_2.png",
    "images_sorting_bars_red_bar_3": "../../shared-resources/images/sorting/Bars/Red_Bar_3.png",
    "images_sorting_bars_red_bar_4": "../../shared-resources/images/sorting/Bars/Red_Bar_4.png",
    "images_sorting_bars_red_bar_5": "../../shared-resources/images/sorting/Bars/Red_Bar_5.png",
    "images_sorting_cards": "../../shared-resources/images/sorting/Cards/",
    "images_sorting_cards_blank_card": "../../shared-resources/images/sorting/Cards/Blank_Card.png",
    "images_sorting_cards_giraffe_card": "../../shared-resources/images/sorting/Cards/Giraffe_Card.png",
    "images_sorting_cards_lion_card": "../../shared-resources/images/sorting/Cards/Lion_Card.png",
    "images_sorting_cards_mouse_card": "../../shared-resources/images/sorting/Cards/Mouse_Card.png",
    "images_sorting_cards_pig_card": "../../shared-resources/images/sorting/Cards/Pig_Card.png",
    "images_sorting_cards_rabbit_card": "../../shared-resources/images/sorting/Cards/Rabbit_Card.png",
    "images_sorting_cards_scorpion_card": "../../shared-resources/images/sorting/Cards/Scorpion_Card.png",
    "images_sorting_dock": "../../shared-resources/images/sorting/Dock.png",
    "images_sorting_key_table": "../../shared-resources/images/sorting/Key_table.png",
    "images_sorting_shapes": "../../shared-resources/images/sorting/shapes/",
    "images_sorting_shapes_equilateral_blue_1": "../../shared-resources/images/sorting/shapes/Equilateral_blue_1.png",
    "images_sorting_shapes_equilateral_green_1": "../../shared-resources/images/sorting/shapes/Equilateral_green_1.png",
    "images_sorting_shapes_equilateral_red_1": "../../shared-resources/images/sorting/shapes/Equilateral_red_1.png",
    "images_sorting_shapes_equilateral_white_1": "../../shared-resources/images/sorting/shapes/Equilateral_white_1.png",
    "images_sorting_shapes_equilateral_yellow_1": "../../shared-resources/images/sorting/shapes/Equilateral_yellow_1.png",
    "images_sorting_shapes_hexagon_white_1": "../../shared-resources/images/sorting/shapes/Hexagon_white_1.png",
    "images_sorting_shapes_isosceles_blue_1": "../../shared-resources/images/sorting/shapes/Isosceles_blue_1.png",
    "images_sorting_shapes_isosceles_green_1": "../../shared-resources/images/sorting/shapes/Isosceles_green_1.png",
    "images_sorting_shapes_isosceles_red_1": "../../shared-resources/images/sorting/shapes/Isosceles_red_1.png",
    "images_sorting_shapes_isosceles_white_1": "../../shared-resources/images/sorting/shapes/Isosceles_white_1.png",
    "images_sorting_shapes_isosceles_yellow_1": "../../shared-resources/images/sorting/shapes/Isosceles_yellow_1.png",
    "images_sorting_shapes_octogun_white_1": "../../shared-resources/images/sorting/shapes/Octogun_white_1.png",
    "images_sorting_shapes_pentagon_white_1": "../../shared-resources/images/sorting/shapes/Pentagon_white_1.png",
    "images_sorting_shapes_rectangle_red_1": "../../shared-resources/images/sorting/shapes/Rectangle_red_1.png",
    "images_sorting_shapes_scalene_blue_1": "../../shared-resources/images/sorting/shapes/Scalene_blue_1.png",
    "images_sorting_shapes_scalene_green_1": "../../shared-resources/images/sorting/shapes/Scalene_green_1.png",
    "images_sorting_shapes_scalene_white_1": "../../shared-resources/images/sorting/shapes/Scalene_white_1.png",
    "images_sorting_shapes_scalene_yellow_1": "../../shared-resources/images/sorting/shapes/Scalene_yellow_1.png",
    "images_sorting_shapes_square_blue_1": "../../shared-resources/images/sorting/shapes/Square_blue_1.png",
    "images_sorting_shapes_square_green_1": "../../shared-resources/images/sorting/shapes/Square_green_1.png",
    "images_sorting_shapes_square_red_1": "../../shared-resources/images/sorting/shapes/Square_red_1.png",
    "images_sorting_shapes_square_white_1": "../../shared-resources/images/sorting/shapes/Square_white_1.png",
    "images_sorting_shapes_square_yellow_1": "../../shared-resources/images/sorting/shapes/Square_yellow_1.png",
    "images_sorting_sorting_box": "../../shared-resources/images/sorting/Sorting_box.png",
    "images_sorting_table_frame": "../../shared-resources/images/sorting/Table_frame.png",
    "images_sorting_venn_diagram2_highlights": "../../shared-resources/images/sorting/Venn_diagram2_highlights/",
    "images_sorting_venn_diagram2_highlights_venn_diagram_2_highlight_centre": "../../shared-resources/images/sorting/Venn_diagram2_highlights/Venn_diagram_2_highlight_Centre.png",
    "images_sorting_venn_diagram2_highlights_venn_diagram_2_highlight_left": "../../shared-resources/images/sorting/Venn_diagram2_highlights/Venn_diagram_2_highlight_left.png",
    "images_sorting_venn_diagram2_highlights_venn_diagram_2_highlight_right": "../../shared-resources/images/sorting/Venn_diagram2_highlights/Venn_diagram_2_highlight_Right.png",
    "images_sorting_venn_diagram3_higlights": "../../shared-resources/images/sorting/Venn_diagram3_higlights/",
    "images_sorting_venn_diagram3_higlights_venn_highlight_bottom": "../../shared-resources/images/sorting/Venn_diagram3_higlights/Venn_Highlight_Bottom.png",
    "images_sorting_venn_diagram3_higlights_venn_highlight_centre": "../../shared-resources/images/sorting/Venn_diagram3_higlights/Venn_Highlight_Centre.png",
    "images_sorting_venn_diagram3_higlights_venn_highlight_left": "../../shared-resources/images/sorting/Venn_diagram3_higlights/Venn_Highlight_Left.png",
    "images_sorting_venn_diagram3_higlights_venn_highlight_right": "../../shared-resources/images/sorting/Venn_diagram3_higlights/Venn_Highlight_Right.png",
    "images_sorting_venn_diagram3_higlights_venn_highlight_top": "../../shared-resources/images/sorting/Venn_diagram3_higlights/Venn_Highlight_Top.png",
    "images_sorting_venn_diagram3_higlights_venn_highlight_top_left": "../../shared-resources/images/sorting/Venn_diagram3_higlights/Venn_Highlight_Top_Left.png",
    "images_sorting_venn_diagram3_higlights_venn_highlight_top_right": "../../shared-resources/images/sorting/Venn_diagram3_higlights/Venn_Highlight_Top_right.png",
    "images_sorting_venn_diagram_2": "../../shared-resources/images/sorting/Venn_diagram_2.png",
    "images_sorting_venn_diagram_3_colour": "../../shared-resources/images/sorting/Venn_diagram_3_colour.png"
};
// Cocos Preloaded Resources
var g_resources = [
    {src:window.bl.resources['images_clock_am']},
    {src:window.bl.resources['images_clock_am_small']},
    {src:window.bl.resources['images_clock_arrow_down']},
    {src:window.bl.resources['images_clock_arrow_down_small']},
    {src:window.bl.resources['images_clock_arrow_up']},
    {src:window.bl.resources['images_clock_arrow_up_small']},
    {src:window.bl.resources['images_clock_clock_cards_clock_card_1']},
    {src:window.bl.resources['images_clock_clock_cards_clock_card_10']},
    {src:window.bl.resources['images_clock_clock_cards_clock_card_11']},
    {src:window.bl.resources['images_clock_clock_cards_clock_card_12']},
    {src:window.bl.resources['images_clock_clock_cards_clock_card_2']},
    {src:window.bl.resources['images_clock_clock_cards_clock_card_3']},
    {src:window.bl.resources['images_clock_clock_cards_clock_card_4']},
    {src:window.bl.resources['images_clock_clock_cards_clock_card_5']},
    {src:window.bl.resources['images_clock_clock_cards_clock_card_6']},
    {src:window.bl.resources['images_clock_clock_cards_clock_card_7']},
    {src:window.bl.resources['images_clock_clock_cards_clock_card_8']},
    {src:window.bl.resources['images_clock_clock_cards_clock_card_9']},
    {src:window.bl.resources['images_clock_clock_centre_pin']},
    {src:window.bl.resources['images_clock_clock_face']},
    {src:window.bl.resources['images_clock_clock_numbers_3_6_9_12']},
    {src:window.bl.resources['images_clock_clock_numbers_all']},
    {src:window.bl.resources['images_clock_digital_bg']},
    {src:window.bl.resources['images_clock_digital_bg_small']},
    {src:window.bl.resources['images_clock_digits_0']},
    {src:window.bl.resources['images_clock_digits_0_small']},
    {src:window.bl.resources['images_clock_digits_1']},
    {src:window.bl.resources['images_clock_digits_1_small']},
    {src:window.bl.resources['images_clock_digits_2']},
    {src:window.bl.resources['images_clock_digits_2_small']},
    {src:window.bl.resources['images_clock_digits_3']},
    {src:window.bl.resources['images_clock_digits_3_small']},
    {src:window.bl.resources['images_clock_digits_4']},
    {src:window.bl.resources['images_clock_digits_4_small']},
    {src:window.bl.resources['images_clock_digits_5']},
    {src:window.bl.resources['images_clock_digits_5_small']},
    {src:window.bl.resources['images_clock_digits_6']},
    {src:window.bl.resources['images_clock_digits_6_small']},
    {src:window.bl.resources['images_clock_digits_7']},
    {src:window.bl.resources['images_clock_digits_7_small']},
    {src:window.bl.resources['images_clock_digits_8']},
    {src:window.bl.resources['images_clock_digits_8_small']},
    {src:window.bl.resources['images_clock_digits_9']},
    {src:window.bl.resources['images_clock_digits_9_small']},
    {src:window.bl.resources['images_clock_digits_colon']},
    {src:window.bl.resources['images_clock_digits_colon_small']},
    {src:window.bl.resources['images_clock_hour_hand']},
    {src:window.bl.resources['images_clock_hour_hand_handle']},
    {src:window.bl.resources['images_clock_minute_hand']},
    {src:window.bl.resources['images_clock_minute_hand_handle']},
    {src:window.bl.resources['images_clock_options_close_button']},
    {src:window.bl.resources['images_clock_options_digital_button_grey']},
    {src:window.bl.resources['images_clock_options_digital_button_orange']},
    {src:window.bl.resources['images_clock_options_hour_button_grey']},
    {src:window.bl.resources['images_clock_options_hour_button_orange']},
    {src:window.bl.resources['images_clock_options_minute_button_grey']},
    {src:window.bl.resources['images_clock_options_minute_button_orange']},
    {src:window.bl.resources['images_clock_options_open_button']},
    {src:window.bl.resources['images_clock_options_panel']},
    {src:window.bl.resources['images_clock_options_sentence_button_grey']},
    {src:window.bl.resources['images_clock_options_sentence_button_orange']},
    {src:window.bl.resources['images_clock_options_words_button_grey']},
    {src:window.bl.resources['images_clock_options_words_button_orange']},
    {src:window.bl.resources['images_clock_pm']},
    {src:window.bl.resources['images_clock_pm_small']},
    {src:window.bl.resources['images_clock_preview_clock_tool_analog']},
    {src:window.bl.resources['images_clock_preview_clock_tool_both']},
    {src:window.bl.resources['images_clock_preview_clock_tool_digital']},
    {src:window.bl.resources['images_clock_settings_12hr_off']},
    {src:window.bl.resources['images_clock_settings_12hr_on']},
    {src:window.bl.resources['images_clock_settings_24hr_off']},
    {src:window.bl.resources['images_clock_settings_24hr_on']},
    {src:window.bl.resources['images_clock_settings_analog_button_off']},
    {src:window.bl.resources['images_clock_settings_analog_button_on']},
    {src:window.bl.resources['images_clock_settings_analoganddigital_button_off']},
    {src:window.bl.resources['images_clock_settings_analoganddigital_button_on']},
    {src:window.bl.resources['images_clock_settings_digital_button_off']},
    {src:window.bl.resources['images_clock_settings_digital_button_on']},
    {src:window.bl.resources['images_clock_settings_free_form_bg']},
    {src:window.bl.resources['images_clock_settings_free_form_closebutton']},
    {src:window.bl.resources['images_clock_settings_markers_off']},
    {src:window.bl.resources['images_clock_settings_markers_on']},
    {src:window.bl.resources['images_clock_settings_numbers_off']},
    {src:window.bl.resources['images_clock_settings_numbers_on']},
    {src:window.bl.resources['images_clock_settings_sentence_off']},
    {src:window.bl.resources['images_clock_settings_sentence_on']},
    {src:window.bl.resources['images_clock_settings_settings_button']},
    {src:window.bl.resources['images_clock_settings_settings_button_base']},
    {src:window.bl.resources['images_clock_settings_words_off']},
    {src:window.bl.resources['images_clock_settings_words_on']},
    {src:window.bl.resources['images_clock_title']},
    {src:window.bl.resources['images_closenormal']},
    {src:window.bl.resources['images_deep_water_background']},
    {src:window.bl.resources['images_geoboard_addpinbutton']},
    {src:window.bl.resources['images_geoboard_anglebackground']},
    {src:window.bl.resources['images_geoboard_arrow_down_button']},
    {src:window.bl.resources['images_geoboard_arrow_up_button']},
    {src:window.bl.resources['images_geoboard_background']},
    {src:window.bl.resources['images_geoboard_band_1_white']},
    {src:window.bl.resources['images_geoboard_band_button']},
    {src:window.bl.resources['images_geoboard_band_button_base']},
    {src:window.bl.resources['images_geoboard_band_circle']},
    {src:window.bl.resources['images_geoboard_bandbutton']},
    {src:window.bl.resources['images_geoboard_bandpart']},
    {src:window.bl.resources['images_geoboard_centrepinbutton']},
    {src:window.bl.resources['images_geoboard_centrepoint_button']},
    {src:window.bl.resources['images_geoboard_circlepin_button']},
    {src:window.bl.resources['images_geoboard_circlepin_button_base']},
    {src:window.bl.resources['images_geoboard_circularbutton']},
    {src:window.bl.resources['images_geoboard_colour_box_empty']},
    {src:window.bl.resources['images_geoboard_colour_select']},
    {src:window.bl.resources['images_geoboard_colour_selected']},
    {src:window.bl.resources['images_geoboard_geoboard_title']},
    {src:window.bl.resources['images_geoboard_hand']},
    {src:window.bl.resources['images_geoboard_hand_up']},
    {src:window.bl.resources['images_geoboard_info_side_button']},
    {src:window.bl.resources['images_geoboard_info_side_button_highlight']},
    {src:window.bl.resources['images_geoboard_inspect_button']},
    {src:window.bl.resources['images_geoboard_isopin_button']},
    {src:window.bl.resources['images_geoboard_isopin_button_base']},
    {src:window.bl.resources['images_geoboard_label_panel']},
    {src:window.bl.resources['images_geoboard_minuspinbutton']},
    {src:window.bl.resources['images_geoboard_newbandbutton']},
    {src:window.bl.resources['images_geoboard_number_box']},
    {src:window.bl.resources['images_geoboard_parallelsidearrow']},
    {src:window.bl.resources['images_geoboard_pin']},
    {src:window.bl.resources['images_geoboard_pin_white']},
    {src:window.bl.resources['images_geoboard_pin_white_noshadow']},
    {src:window.bl.resources['images_geoboard_pinboardbackground']},
    {src:window.bl.resources['images_geoboard_propertybackground']},
    {src:window.bl.resources['images_geoboard_removebandbutton']},
    {src:window.bl.resources['images_geoboard_rubberband_base']},
    {src:window.bl.resources['images_geoboard_rubberband_icon']},
    {src:window.bl.resources['images_geoboard_sameanglebutton']},
    {src:window.bl.resources['images_geoboard_sameanglebuttonselected']},
    {src:window.bl.resources['images_geoboard_samesidelengthbutton']},
    {src:window.bl.resources['images_geoboard_samesidelengthbuttonselected']},
    {src:window.bl.resources['images_geoboard_samesidelengthnotch']},
    {src:window.bl.resources['images_geoboard_showanglesbutton']},
    {src:window.bl.resources['images_geoboard_showanglesbuttonselected']},
    {src:window.bl.resources['images_geoboard_showparallelsidesbutton']},
    {src:window.bl.resources['images_geoboard_showparallelsidesbuttonselected']},
    {src:window.bl.resources['images_geoboard_showsidelengthsbutton']},
    {src:window.bl.resources['images_geoboard_showsidelengthsbuttonselected']},
    {src:window.bl.resources['images_geoboard_sidelabelbackground']},
    {src:window.bl.resources['images_geoboard_singlebandpart']},
    {src:window.bl.resources['images_geoboard_squarelatticebutton']},
    {src:window.bl.resources['images_geoboard_squarepin_button']},
    {src:window.bl.resources['images_geoboard_squarepin_button_base']},
    {src:window.bl.resources['images_geoboard_trash_button']},
    {src:window.bl.resources['images_geoboard_trash_button_base']},
    {src:window.bl.resources['images_geoboard_triangularlatticebutton']},
    {src:window.bl.resources['images_geoboard_whitepin']},
    {src:window.bl.resources['images_object']},
    {src:window.bl.resources['images_sand_background']},
    {src:window.bl.resources['images_sorting_barchart_axis_x']},
    {src:window.bl.resources['images_sorting_barchart_axis_y']},
    {src:window.bl.resources['images_sorting_bars_blue_bar_1']},
    {src:window.bl.resources['images_sorting_bars_blue_bar_2']},
    {src:window.bl.resources['images_sorting_bars_blue_bar_3']},
    {src:window.bl.resources['images_sorting_bars_blue_bar_4']},
    {src:window.bl.resources['images_sorting_bars_blue_bar_5']},
    {src:window.bl.resources['images_sorting_bars_green_bar_1']},
    {src:window.bl.resources['images_sorting_bars_green_bar_2']},
    {src:window.bl.resources['images_sorting_bars_green_bar_3']},
    {src:window.bl.resources['images_sorting_bars_green_bar_4']},
    {src:window.bl.resources['images_sorting_bars_green_bar_5']},
    {src:window.bl.resources['images_sorting_bars_orange_bar_1']},
    {src:window.bl.resources['images_sorting_bars_orange_bar_2']},
    {src:window.bl.resources['images_sorting_bars_orange_bar_3']},
    {src:window.bl.resources['images_sorting_bars_orange_bar_4']},
    {src:window.bl.resources['images_sorting_bars_orange_bar_5']},
    {src:window.bl.resources['images_sorting_bars_pink_bar_1']},
    {src:window.bl.resources['images_sorting_bars_pink_bar_2']},
    {src:window.bl.resources['images_sorting_bars_pink_bar_3']},
    {src:window.bl.resources['images_sorting_bars_pink_bar_4']},
    {src:window.bl.resources['images_sorting_bars_pink_bar_5']},
    {src:window.bl.resources['images_sorting_bars_red_bar_1']},
    {src:window.bl.resources['images_sorting_bars_red_bar_2']},
    {src:window.bl.resources['images_sorting_bars_red_bar_3']},
    {src:window.bl.resources['images_sorting_bars_red_bar_4']},
    {src:window.bl.resources['images_sorting_bars_red_bar_5']},
    {src:window.bl.resources['images_sorting_cards_blank_card']},
    {src:window.bl.resources['images_sorting_cards_giraffe_card']},
    {src:window.bl.resources['images_sorting_cards_lion_card']},
    {src:window.bl.resources['images_sorting_cards_mouse_card']},
    {src:window.bl.resources['images_sorting_cards_pig_card']},
    {src:window.bl.resources['images_sorting_cards_rabbit_card']},
    {src:window.bl.resources['images_sorting_cards_scorpion_card']},
    {src:window.bl.resources['images_sorting_dock']},
    {src:window.bl.resources['images_sorting_key_table']},
    {src:window.bl.resources['images_sorting_shapes_equilateral_blue_1']},
    {src:window.bl.resources['images_sorting_shapes_equilateral_green_1']},
    {src:window.bl.resources['images_sorting_shapes_equilateral_red_1']},
    {src:window.bl.resources['images_sorting_shapes_equilateral_white_1']},
    {src:window.bl.resources['images_sorting_shapes_equilateral_yellow_1']},
    {src:window.bl.resources['images_sorting_shapes_hexagon_white_1']},
    {src:window.bl.resources['images_sorting_shapes_isosceles_blue_1']},
    {src:window.bl.resources['images_sorting_shapes_isosceles_green_1']},
    {src:window.bl.resources['images_sorting_shapes_isosceles_red_1']},
    {src:window.bl.resources['images_sorting_shapes_isosceles_white_1']},
    {src:window.bl.resources['images_sorting_shapes_isosceles_yellow_1']},
    {src:window.bl.resources['images_sorting_shapes_octogun_white_1']},
    {src:window.bl.resources['images_sorting_shapes_pentagon_white_1']},
    {src:window.bl.resources['images_sorting_shapes_rectangle_red_1']},
    {src:window.bl.resources['images_sorting_shapes_scalene_blue_1']},
    {src:window.bl.resources['images_sorting_shapes_scalene_green_1']},
    {src:window.bl.resources['images_sorting_shapes_scalene_white_1']},
    {src:window.bl.resources['images_sorting_shapes_scalene_yellow_1']},
    {src:window.bl.resources['images_sorting_shapes_square_blue_1']},
    {src:window.bl.resources['images_sorting_shapes_square_green_1']},
    {src:window.bl.resources['images_sorting_shapes_square_red_1']},
    {src:window.bl.resources['images_sorting_shapes_square_white_1']},
    {src:window.bl.resources['images_sorting_shapes_square_yellow_1']},
    {src:window.bl.resources['images_sorting_sorting_box']},
    {src:window.bl.resources['images_sorting_table_frame']},
    {src:window.bl.resources['images_sorting_venn_diagram2_highlights_venn_diagram_2_highlight_centre']},
    {src:window.bl.resources['images_sorting_venn_diagram2_highlights_venn_diagram_2_highlight_left']},
    {src:window.bl.resources['images_sorting_venn_diagram2_highlights_venn_diagram_2_highlight_right']},
    {src:window.bl.resources['images_sorting_venn_diagram3_higlights_venn_highlight_bottom']},
    {src:window.bl.resources['images_sorting_venn_diagram3_higlights_venn_highlight_centre']},
    {src:window.bl.resources['images_sorting_venn_diagram3_higlights_venn_highlight_left']},
    {src:window.bl.resources['images_sorting_venn_diagram3_higlights_venn_highlight_right']},
    {src:window.bl.resources['images_sorting_venn_diagram3_higlights_venn_highlight_top']},
    {src:window.bl.resources['images_sorting_venn_diagram3_higlights_venn_highlight_top_left']},
    {src:window.bl.resources['images_sorting_venn_diagram3_higlights_venn_highlight_top_right']},
    {src:window.bl.resources['images_sorting_venn_diagram_2']},
    {src:window.bl.resources['images_sorting_venn_diagram_3_colour']}
];
