
window.bl = window.bl || {};
window.bl.resources = {
    "images_closenormal": "../../shared-resources/images/CloseNormal.png",
    "images_deep_water_background": "../../shared-resources/images/deep_water_background.png",
    "images_object": "../../shared-resources/images/object.png",
    "images_sand_background": "../../shared-resources/images/sand_background.jpg",
    "images_tooltip": "../../shared-resources/images/ToolTip.png",
    "clock_am": "../../tools/clock/resources/AM.png",
    "clock_am_small": "../../tools/clock/resources/AM_Small.png",
    "clock_arrow_down": "../../tools/clock/resources/Arrow_Down.png",
    "clock_arrow_down_small": "../../tools/clock/resources/Arrow_Down_Small.png",
    "clock_arrow_up": "../../tools/clock/resources/Arrow_Up.png",
    "clock_arrow_up_small": "../../tools/clock/resources/Arrow_Up_Small.png",
    "clock_clock_cards_clock_card_1": "../../tools/clock/resources/clock_cards/Clock_Card_1.png",
    "clock_clock_cards_clock_card_10": "../../tools/clock/resources/clock_cards/Clock_Card_10.png",
    "clock_clock_cards_clock_card_11": "../../tools/clock/resources/clock_cards/Clock_Card_11.png",
    "clock_clock_cards_clock_card_12": "../../tools/clock/resources/clock_cards/Clock_Card_12.png",
    "clock_clock_cards_clock_card_2": "../../tools/clock/resources/clock_cards/Clock_Card_2.png",
    "clock_clock_cards_clock_card_3": "../../tools/clock/resources/clock_cards/Clock_Card_3.png",
    "clock_clock_cards_clock_card_4": "../../tools/clock/resources/clock_cards/Clock_Card_4.png",
    "clock_clock_cards_clock_card_5": "../../tools/clock/resources/clock_cards/Clock_Card_5.png",
    "clock_clock_cards_clock_card_6": "../../tools/clock/resources/clock_cards/Clock_Card_6.png",
    "clock_clock_cards_clock_card_7": "../../tools/clock/resources/clock_cards/Clock_Card_7.png",
    "clock_clock_cards_clock_card_8": "../../tools/clock/resources/clock_cards/Clock_Card_8.png",
    "clock_clock_cards_clock_card_9": "../../tools/clock/resources/clock_cards/Clock_Card_9.png",
    "clock_clock_centre_pin": "../../tools/clock/resources/Clock_Centre_Pin.png",
    "clock_clock_face": "../../tools/clock/resources/Clock_Face.png",
    "clock_clock_numbers_3_6_9_12": "../../tools/clock/resources/Clock_Numbers_3-6-9-12.png",
    "clock_clock_numbers_all": "../../tools/clock/resources/Clock_Numbers_All.png",
    "clock_digital_bg": "../../tools/clock/resources/digital_bg.png",
    "clock_digital_bg_small": "../../tools/clock/resources/digital_bg_Small.png",
    "clock_digits_0": "../../tools/clock/resources/digits/0.png",
    "clock_digits_0_small": "../../tools/clock/resources/digits/0_Small.png",
    "clock_digits_1": "../../tools/clock/resources/digits/1.png",
    "clock_digits_1_small": "../../tools/clock/resources/digits/1_Small.png",
    "clock_digits_2": "../../tools/clock/resources/digits/2.png",
    "clock_digits_2_small": "../../tools/clock/resources/digits/2_Small.png",
    "clock_digits_3": "../../tools/clock/resources/digits/3.png",
    "clock_digits_3_small": "../../tools/clock/resources/digits/3_Small.png",
    "clock_digits_4": "../../tools/clock/resources/digits/4.png",
    "clock_digits_4_small": "../../tools/clock/resources/digits/4_Small.png",
    "clock_digits_5": "../../tools/clock/resources/digits/5.png",
    "clock_digits_5_small": "../../tools/clock/resources/digits/5_Small.png",
    "clock_digits_6": "../../tools/clock/resources/digits/6.png",
    "clock_digits_6_small": "../../tools/clock/resources/digits/6_Small.png",
    "clock_digits_7": "../../tools/clock/resources/digits/7.png",
    "clock_digits_7_small": "../../tools/clock/resources/digits/7_Small.png",
    "clock_digits_8": "../../tools/clock/resources/digits/8.png",
    "clock_digits_8_small": "../../tools/clock/resources/digits/8_Small.png",
    "clock_digits_9": "../../tools/clock/resources/digits/9.png",
    "clock_digits_9_small": "../../tools/clock/resources/digits/9_Small.png",
    "clock_digits_colon": "../../tools/clock/resources/digits/colon.png",
    "clock_digits_colon_small": "../../tools/clock/resources/digits/colon_Small.png",
    "clock_hour_hand": "../../tools/clock/resources/Hour_hand.png",
    "clock_hour_hand_handle": "../../tools/clock/resources/Hour_hand_handle.png",
    "clock_minute_hand": "../../tools/clock/resources/Minute_hand.png",
    "clock_minute_hand_handle": "../../tools/clock/resources/Minute_hand_handle.png",
    "clock_options_close_button": "../../tools/clock/resources/Options_Close_button.png",
    "clock_options_digital_button_grey": "../../tools/clock/resources/Options_Digital_button_grey.png",
    "clock_options_digital_button_orange": "../../tools/clock/resources/Options_Digital_button_Orange.png",
    "clock_options_hour_button_grey": "../../tools/clock/resources/Options_Hour_button_grey.png",
    "clock_options_hour_button_orange": "../../tools/clock/resources/Options_Hour_button_Orange.png",
    "clock_options_minute_button_grey": "../../tools/clock/resources/Options_Minute_button_grey.png",
    "clock_options_minute_button_orange": "../../tools/clock/resources/Options_Minute_button_Orange.png",
    "clock_options_open_button": "../../tools/clock/resources/Options_Open_button.png",
    "clock_options_panel": "../../tools/clock/resources/Options_Panel.png",
    "clock_options_sentence_button_grey": "../../tools/clock/resources/Options_Sentence_button_grey.png",
    "clock_options_sentence_button_orange": "../../tools/clock/resources/Options_Sentence_button_Orange.png",
    "clock_options_words_button_grey": "../../tools/clock/resources/Options_Words_button_grey.png",
    "clock_options_words_button_orange": "../../tools/clock/resources/Options_Words_button_Orange.png",
    "clock_pm": "../../tools/clock/resources/PM.png",
    "clock_pm_small": "../../tools/clock/resources/PM_Small.png",
    "clock_settings_12hr_off": "../../tools/clock/resources/settings/12hr_Off.png",
    "clock_settings_12hr_on": "../../tools/clock/resources/settings/12hr_On.png",
    "clock_settings_24hr_off": "../../tools/clock/resources/settings/24hr_Off.png",
    "clock_settings_24hr_on": "../../tools/clock/resources/settings/24hr_On.png",
    "clock_settings_analog_button_off": "../../tools/clock/resources/settings/Analog_Button_Off.png",
    "clock_settings_analog_button_on": "../../tools/clock/resources/settings/Analog_Button_On.png",
    "clock_settings_analoganddigital_button_off": "../../tools/clock/resources/settings/AnalogAndDigital_Button_Off.png",
    "clock_settings_analoganddigital_button_on": "../../tools/clock/resources/settings/AnalogAndDigital_Button_On.png",
    "clock_settings_digital_button_off": "../../tools/clock/resources/settings/Digital_Button_Off.png",
    "clock_settings_digital_button_on": "../../tools/clock/resources/settings/Digital_Button_On.png",
    "clock_settings_free_form_bg": "../../tools/clock/resources/settings/Free_Form_BG.png",
    "clock_settings_free_form_closebutton": "../../tools/clock/resources/settings/Free_Form_CloseButton.png",
    "clock_settings_markers_off": "../../tools/clock/resources/settings/Markers_Off.png",
    "clock_settings_markers_on": "../../tools/clock/resources/settings/Markers_On.png",
    "clock_settings_numbers_off": "../../tools/clock/resources/settings/Numbers_Off.png",
    "clock_settings_numbers_on": "../../tools/clock/resources/settings/Numbers_On.png",
    "clock_settings_sentence_off": "../../tools/clock/resources/settings/Sentence_Off.png",
    "clock_settings_sentence_on": "../../tools/clock/resources/settings/Sentence_On.png",
    "clock_settings_settings_button": "../../tools/clock/resources/settings/Settings_button.png",
    "clock_settings_settings_button_base": "../../tools/clock/resources/settings/Settings_button_base.png",
    "clock_settings_words_off": "../../tools/clock/resources/settings/Words_Off.png",
    "clock_settings_words_on": "../../tools/clock/resources/settings/Words_On.png",
    "clock_title": "../../tools/clock/resources/Title.png",
    "geoboard_addpinbutton": "../../tools/geoboard/resources/addPinButton.png",
    "geoboard_anglebackground": "../../tools/geoboard/resources/angleBackground.png",
    "geoboard_arrow_down_button": "../../tools/geoboard/resources/Arrow_down_button.png",
    "geoboard_arrow_up_button": "../../tools/geoboard/resources/Arrow_up_button.png",
    "geoboard_background": "../../tools/geoboard/resources/background.png",
    "geoboard_band_1_white": "../../tools/geoboard/resources/Band_1_white.png",
    "geoboard_band_button": "../../tools/geoboard/resources/Band_button.png",
    "geoboard_band_button_base": "../../tools/geoboard/resources/Band_button_base.png",
    "geoboard_band_circle": "../../tools/geoboard/resources/Band_Circle.png",
    "geoboard_bandbutton": "../../tools/geoboard/resources/bandButton.png",
    "geoboard_bandpart": "../../tools/geoboard/resources/bandPart.png",
    "geoboard_centrepinbutton": "../../tools/geoboard/resources/centrePinButton.png",
    "geoboard_centrepoint_button": "../../tools/geoboard/resources/CentrePoint_button.png",
    "geoboard_circlepin_button": "../../tools/geoboard/resources/CirclePin_button.png",
    "geoboard_circlepin_button_base": "../../tools/geoboard/resources/CirclePin_button_base.png",
    "geoboard_circularbutton": "../../tools/geoboard/resources/circularButton.png",
    "geoboard_colour_box_empty": "../../tools/geoboard/resources/colour_box_empty.png",
    "geoboard_colour_select": "../../tools/geoboard/resources/Colour_select.png",
    "geoboard_colour_selected": "../../tools/geoboard/resources/colour_selected.png",
    "geoboard_geoboard_title": "../../tools/geoboard/resources/Geoboard_title.png",
    "geoboard_hand": "../../tools/geoboard/resources/Hand.png",
    "geoboard_hand_up": "../../tools/geoboard/resources/hand_up.png",
    "geoboard_info_side_button": "../../tools/geoboard/resources/Info_Side_Button.png",
    "geoboard_info_side_button_highlight": "../../tools/geoboard/resources/Info_Side_Button_highlight.png",
    "geoboard_inspect_button": "../../tools/geoboard/resources/Inspect_button.png",
    "geoboard_isopin_button": "../../tools/geoboard/resources/IsoPin_button.png",
    "geoboard_isopin_button_base": "../../tools/geoboard/resources/IsoPin_button_base.png",
    "geoboard_label_panel": "../../tools/geoboard/resources/label_panel.png",
    "geoboard_minuspinbutton": "../../tools/geoboard/resources/minusPinButton.png",
    "geoboard_newbandbutton": "../../tools/geoboard/resources/newBandButton.png",
    "geoboard_number_box": "../../tools/geoboard/resources/Number_box.png",
    "geoboard_parallelsidearrow": "../../tools/geoboard/resources/parallelSideArrow.png",
    "geoboard_pin": "../../tools/geoboard/resources/pin.png",
    "geoboard_pin_white": "../../tools/geoboard/resources/Pin_white.png",
    "geoboard_pin_white_noshadow": "../../tools/geoboard/resources/Pin_white_noShadow.png",
    "geoboard_pinboardbackground": "../../tools/geoboard/resources/pinboardBackground.png",
    "geoboard_propertybackground": "../../tools/geoboard/resources/propertyBackground.png",
    "geoboard_removebandbutton": "../../tools/geoboard/resources/removeBandButton.png",
    "geoboard_rubberband_base": "../../tools/geoboard/resources/RubberBand_base.png",
    "geoboard_rubberband_icon": "../../tools/geoboard/resources/RubberBand_Icon.png",
    "geoboard_sameanglebutton": "../../tools/geoboard/resources/sameAngleButton.png",
    "geoboard_sameanglebuttonselected": "../../tools/geoboard/resources/sameAngleButtonSelected.png",
    "geoboard_samesidelengthbutton": "../../tools/geoboard/resources/sameSideLengthButton.png",
    "geoboard_samesidelengthbuttonselected": "../../tools/geoboard/resources/sameSideLengthButtonSelected.png",
    "geoboard_samesidelengthnotch": "../../tools/geoboard/resources/sameSideLengthNotch.png",
    "geoboard_showanglesbutton": "../../tools/geoboard/resources/showAnglesButton.png",
    "geoboard_showanglesbuttonselected": "../../tools/geoboard/resources/showAnglesButtonSelected.png",
    "geoboard_showparallelsidesbutton": "../../tools/geoboard/resources/showParallelSidesButton.png",
    "geoboard_showparallelsidesbuttonselected": "../../tools/geoboard/resources/showParallelSidesButtonSelected.png",
    "geoboard_showsidelengthsbutton": "../../tools/geoboard/resources/showSideLengthsButton.png",
    "geoboard_showsidelengthsbuttonselected": "../../tools/geoboard/resources/showSideLengthsButtonSelected.png",
    "geoboard_sidelabelbackground": "../../tools/geoboard/resources/sideLabelBackground.png",
    "geoboard_singlebandpart": "../../tools/geoboard/resources/singleBandPart.png",
    "geoboard_squarelatticebutton": "../../tools/geoboard/resources/squareLatticeButton.png",
    "geoboard_squarepin_button": "../../tools/geoboard/resources/SquarePin_button.png",
    "geoboard_squarepin_button_base": "../../tools/geoboard/resources/SquarePin_button_base.png",
    "geoboard_trash_button": "../../tools/geoboard/resources/trash_button.png",
    "geoboard_trash_button_base": "../../tools/geoboard/resources/trash_button_base.png",
    "geoboard_triangularlatticebutton": "../../tools/geoboard/resources/triangularLatticeButton.png",
    "geoboard_whitepin": "../../tools/geoboard/resources/whitePin.png",
    "longdivision_bar_slither_white": "../../tools/longdivision/resources/Bar_Slither_White.png",
    "longdivision_bar_slither_white_left": "../../tools/longdivision/resources/Bar_Slither_White_Left.png",
    "longdivision_bar_slither_white_right": "../../tools/longdivision/resources/Bar_Slither_White_Right.png",
    "longdivision_barsbox": "../../tools/longdivision/resources/BarsBox.png",
    "longdivision_clear_button": "../../tools/longdivision/resources/Clear_Button.png",
    "longdivision_decimalpoint": "../../tools/longdivision/resources/DecimalPoint.png",
    "longdivision_digitchangehitzone": "../../tools/longdivision/resources/digitChangeHitZone.png",
    "longdivision_labels_label_1": "../../tools/longdivision/resources/labels/label_1.png",
    "longdivision_labels_label_10+1": "../../tools/longdivision/resources/labels/label_10+1.png",
    "longdivision_labels_label_10+2": "../../tools/longdivision/resources/labels/label_10+2.png",
    "longdivision_labels_label_10+3": "../../tools/longdivision/resources/labels/label_10+3.png",
    "longdivision_labels_label_10+4": "../../tools/longdivision/resources/labels/label_10+4.png",
    "longdivision_labels_label_10_1": "../../tools/longdivision/resources/labels/label_10-1.png",
    "longdivision_labels_label_10_2": "../../tools/longdivision/resources/labels/label_10-2.png",
    "longdivision_labels_label_10_3": "../../tools/longdivision/resources/labels/label_10-3.png",
    "longdivision_labels_label_10": "../../tools/longdivision/resources/labels/label_10.png",
    "longdivision_labels_label_100": "../../tools/longdivision/resources/labels/label_100.png",
    "longdivision_labels_label_1000": "../../tools/longdivision/resources/labels/label_1000.png",
    "longdivision_labels_label_1over10": "../../tools/longdivision/resources/labels/label_1over10.png",
    "longdivision_labels_label_1over100": "../../tools/longdivision/resources/labels/label_1over100.png",
    "longdivision_labels_label_1over1000": "../../tools/longdivision/resources/labels/label_1over1000.png",
    "longdivision_labels_label_hundreds": "../../tools/longdivision/resources/labels/label_hundreds.png",
    "longdivision_labels_label_hundredths": "../../tools/longdivision/resources/labels/label_hundredths.png",
    "longdivision_labels_label_number10": "../../tools/longdivision/resources/labels/label_number10.png",
    "longdivision_labels_label_tens": "../../tools/longdivision/resources/labels/label_Tens.png",
    "longdivision_labels_label_tenths": "../../tools/longdivision/resources/labels/label_tenths.png",
    "longdivision_labels_label_thousands": "../../tools/longdivision/resources/labels/label_thousands.png",
    "longdivision_labels_label_thousandths": "../../tools/longdivision/resources/labels/label_thousandths.png",
    "longdivision_labels_label_units": "../../tools/longdivision/resources/labels/label_Units.png",
    "longdivision_magnifyingglass": "../../tools/longdivision/resources/MagnifyingGlass.png",
    "longdivision_number_wheel_numberwheelsectionbackground": "../../tools/longdivision/resources/number_wheel/numberWheelSectionBackground.png",
    "longdivision_number_wheel_nw_1_ov": "../../tools/longdivision/resources/number_wheel/NW_1_ov.png",
    "longdivision_number_wheel_nw_2_ov": "../../tools/longdivision/resources/number_wheel/NW_2_ov.png",
    "longdivision_number_wheel_nw_3_ov": "../../tools/longdivision/resources/number_wheel/NW_3_ov.png",
    "longdivision_number_wheel_nw_4_ov": "../../tools/longdivision/resources/number_wheel/NW_4_ov.png",
    "longdivision_number_wheel_nw_5_ov": "../../tools/longdivision/resources/number_wheel/NW_5_ov.png",
    "longdivision_number_wheel_nw_6_ov": "../../tools/longdivision/resources/number_wheel/NW_6_ov.png",
    "longdivision_numberbox": "../../tools/longdivision/resources/NumberBox.png",
    "longdivision_numberpicker_box": "../../tools/longdivision/resources/NumberPicker_Box.png",
    "longdivision_numberpicker_down_arrow": "../../tools/longdivision/resources/NumberPicker_Down_Arrow.png",
    "longdivision_numberpicker_left_arrow": "../../tools/longdivision/resources/NumberPicker_Left_Arrow.png",
    "longdivision_numberpicker_number_bg": "../../tools/longdivision/resources/NumberPicker_Number_BG.png",
    "longdivision_numberpicker_right_arrow": "../../tools/longdivision/resources/NumberPicker_Right_Arrow.png",
    "longdivision_numberpicker_up_arrow": "../../tools/longdivision/resources/NumberPicker_Up_Arrow.png",
    "longdivision_numberpickerbox": "../../tools/longdivision/resources/NumberPickerBox.png",
    "longdivision_numberwheel_down_arrow": "../../tools/longdivision/resources/NumberWheel_Down_Arrow.png",
    "longdivision_numberwheel_up_arrow": "../../tools/longdivision/resources/NumberWheel_Up_Arrow.png",
    "longdivision_question_tray": "../../tools/longdivision/resources/Question_Tray.png",
    "longdivision_reset_button": "../../tools/longdivision/resources/Reset_Button.png",
    "longdivision_settings_free_form_closebutton": "../../tools/longdivision/resources/settings/Free_Form_CloseButton.png",
    "longdivision_settings_label_off": "../../tools/longdivision/resources/settings/Label_Off.png",
    "longdivision_settings_label_on": "../../tools/longdivision/resources/settings/Label_On.png",
    "longdivision_settings_long_div_settings_bg": "../../tools/longdivision/resources/settings/Long_Div_Settings_BG.png",
    "longdivision_settings_numbers_off": "../../tools/longdivision/resources/settings/Numbers_Off.png",
    "longdivision_settings_numbers_on": "../../tools/longdivision/resources/settings/Numbers_On.png",
    "longdivision_settings_powers_off": "../../tools/longdivision/resources/settings/Powers_Off.png",
    "longdivision_settings_powers_on": "../../tools/longdivision/resources/settings/Powers_On.png",
    "longdivision_settings_settings_button": "../../tools/longdivision/resources/settings/Settings_button.png",
    "longdivision_settings_settings_button_base": "../../tools/longdivision/resources/settings/Settings_button_base.png",
    "longdivision_settings_table_off": "../../tools/longdivision/resources/settings/Table_Off.png",
    "longdivision_settings_table_on": "../../tools/longdivision/resources/settings/Table_On.png",
    "longdivision_single_white_pixel": "../../tools/longdivision/resources/single_white_pixel.png",
    "longdivision_table_=": "../../tools/longdivision/resources/Table_=.png",
    "longdivision_table_answerbox": "../../tools/longdivision/resources/Table_AnswerBox.png",
    "longdivision_table_box": "../../tools/longdivision/resources/Table_Box.png",
    "longdivision_table_down_arrow": "../../tools/longdivision/resources/Table_Down_Arrow.png",
    "longdivision_table_sectionbox": "../../tools/longdivision/resources/Table_SectionBox.png",
    "longdivision_table_up_arrow": "../../tools/longdivision/resources/Table_Up_Arrow.png",
    "longdivision_table_x": "../../tools/longdivision/resources/Table_x.png",
    "longdivision_testbigwhitebox": "../../tools/longdivision/resources/testBigWhiteBox.png",
    "longdivision_title_longdivision": "../../tools/longdivision/resources/Title_longDivision.png",
    "sorting_barchart_axis_x": "../../tools/sorting/resources/BarChart_Axis_X.png",
    "sorting_barchart_axis_y": "../../tools/sorting/resources/BarChart_Axis_Y.png",
    "sorting_barchart_base": "../../tools/sorting/resources/BarChart_Base.png",
    "sorting_bars_blue_bar_1": "../../tools/sorting/resources/Bars/Blue_Bar_1.png",
    "sorting_bars_blue_bar_2": "../../tools/sorting/resources/Bars/Blue_Bar_2.png",
    "sorting_bars_blue_bar_3": "../../tools/sorting/resources/Bars/Blue_Bar_3.png",
    "sorting_bars_blue_bar_4": "../../tools/sorting/resources/Bars/Blue_Bar_4.png",
    "sorting_bars_blue_bar_5": "../../tools/sorting/resources/Bars/Blue_Bar_5.png",
    "sorting_bars_green_bar_1": "../../tools/sorting/resources/Bars/Green_Bar_1.png",
    "sorting_bars_green_bar_2": "../../tools/sorting/resources/Bars/Green_Bar_2.png",
    "sorting_bars_green_bar_3": "../../tools/sorting/resources/Bars/Green_Bar_3.png",
    "sorting_bars_green_bar_4": "../../tools/sorting/resources/Bars/Green_Bar_4.png",
    "sorting_bars_green_bar_5": "../../tools/sorting/resources/Bars/Green_Bar_5.png",
    "sorting_bars_orange_bar_1": "../../tools/sorting/resources/Bars/Orange_Bar_1.png",
    "sorting_bars_orange_bar_2": "../../tools/sorting/resources/Bars/Orange_Bar_2.png",
    "sorting_bars_orange_bar_3": "../../tools/sorting/resources/Bars/Orange_Bar_3.png",
    "sorting_bars_orange_bar_4": "../../tools/sorting/resources/Bars/Orange_Bar_4.png",
    "sorting_bars_orange_bar_5": "../../tools/sorting/resources/Bars/Orange_Bar_5.png",
    "sorting_bars_pink_bar_1": "../../tools/sorting/resources/Bars/Pink_Bar_1.png",
    "sorting_bars_pink_bar_2": "../../tools/sorting/resources/Bars/Pink_Bar_2.png",
    "sorting_bars_pink_bar_3": "../../tools/sorting/resources/Bars/Pink_Bar_3.png",
    "sorting_bars_pink_bar_4": "../../tools/sorting/resources/Bars/Pink_Bar_4.png",
    "sorting_bars_pink_bar_5": "../../tools/sorting/resources/Bars/Pink_Bar_5.png",
    "sorting_bars_red_bar_1": "../../tools/sorting/resources/Bars/Red_Bar_1.png",
    "sorting_bars_red_bar_2": "../../tools/sorting/resources/Bars/Red_Bar_2.png",
    "sorting_bars_red_bar_3": "../../tools/sorting/resources/Bars/Red_Bar_3.png",
    "sorting_bars_red_bar_4": "../../tools/sorting/resources/Bars/Red_Bar_4.png",
    "sorting_bars_red_bar_5": "../../tools/sorting/resources/Bars/Red_Bar_5.png",
    "sorting_cards_blank_card": "../../tools/sorting/resources/Cards/Blank_Card.png",
    "sorting_cards_character_card_assets_eyes_1": "../../tools/sorting/resources/Cards/Character_Card_Assets/eyes_1.png",
    "sorting_cards_character_card_assets_eyes_2": "../../tools/sorting/resources/Cards/Character_Card_Assets/eyes_2.png",
    "sorting_cards_character_card_assets_eyes_3": "../../tools/sorting/resources/Cards/Character_Card_Assets/eyes_3.png",
    "sorting_cards_character_card_assets_horns": "../../tools/sorting/resources/Cards/Character_Card_Assets/horns.png",
    "sorting_cards_character_card_assets_mask_legs_2": "../../tools/sorting/resources/Cards/Character_Card_Assets/Mask_Legs_2.png",
    "sorting_cards_character_card_assets_mask_legs_3": "../../tools/sorting/resources/Cards/Character_Card_Assets/Mask_Legs_3.png",
    "sorting_cards_character_card_assets_mask_legs_4": "../../tools/sorting/resources/Cards/Character_Card_Assets/Mask_Legs_4.png",
    "sorting_cards_giraffe_card": "../../tools/sorting/resources/Cards/Giraffe_Card.png",
    "sorting_cards_lion_card": "../../tools/sorting/resources/Cards/Lion_Card.png",
    "sorting_cards_mouse_card": "../../tools/sorting/resources/Cards/Mouse_Card.png",
    "sorting_cards_pig_card": "../../tools/sorting/resources/Cards/Pig_Card.png",
    "sorting_cards_rabbit_card": "../../tools/sorting/resources/Cards/Rabbit_Card.png",
    "sorting_cards_scorpion_card": "../../tools/sorting/resources/Cards/Scorpion_Card.png",
    "sorting_dock": "../../tools/sorting/resources/Dock.png",
    "sorting_key_table": "../../tools/sorting/resources/Key_table.png",
    "sorting_shapes_equilateral_blue_1": "../../tools/sorting/resources/shapes/Equilateral_blue_1.png",
    "sorting_shapes_equilateral_green_1": "../../tools/sorting/resources/shapes/Equilateral_green_1.png",
    "sorting_shapes_equilateral_red_1": "../../tools/sorting/resources/shapes/Equilateral_red_1.png",
    "sorting_shapes_equilateral_white_1": "../../tools/sorting/resources/shapes/Equilateral_white_1.png",
    "sorting_shapes_equilateral_yellow_1": "../../tools/sorting/resources/shapes/Equilateral_yellow_1.png",
    "sorting_shapes_hexagon_white_1": "../../tools/sorting/resources/shapes/Hexagon_white_1.png",
    "sorting_shapes_isosceles_blue_1": "../../tools/sorting/resources/shapes/Isosceles_blue_1.png",
    "sorting_shapes_isosceles_green_1": "../../tools/sorting/resources/shapes/Isosceles_green_1.png",
    "sorting_shapes_isosceles_red_1": "../../tools/sorting/resources/shapes/Isosceles_red_1.png",
    "sorting_shapes_isosceles_white_1": "../../tools/sorting/resources/shapes/Isosceles_white_1.png",
    "sorting_shapes_isosceles_yellow_1": "../../tools/sorting/resources/shapes/Isosceles_yellow_1.png",
    "sorting_shapes_octogun_white_1": "../../tools/sorting/resources/shapes/Octogun_white_1.png",
    "sorting_shapes_pentagon_white_1": "../../tools/sorting/resources/shapes/Pentagon_white_1.png",
    "sorting_shapes_rectangle_red_1": "../../tools/sorting/resources/shapes/Rectangle_red_1.png",
    "sorting_shapes_scalene_blue_1": "../../tools/sorting/resources/shapes/Scalene_blue_1.png",
    "sorting_shapes_scalene_green_1": "../../tools/sorting/resources/shapes/Scalene_green_1.png",
    "sorting_shapes_scalene_white_1": "../../tools/sorting/resources/shapes/Scalene_white_1.png",
    "sorting_shapes_scalene_yellow_1": "../../tools/sorting/resources/shapes/Scalene_yellow_1.png",
    "sorting_shapes_square_blue_1": "../../tools/sorting/resources/shapes/Square_blue_1.png",
    "sorting_shapes_square_green_1": "../../tools/sorting/resources/shapes/Square_green_1.png",
    "sorting_shapes_square_red_1": "../../tools/sorting/resources/shapes/Square_red_1.png",
    "sorting_shapes_square_white_1": "../../tools/sorting/resources/shapes/Square_white_1.png",
    "sorting_shapes_square_yellow_1": "../../tools/sorting/resources/shapes/Square_yellow_1.png",
    "sorting_sorting_box": "../../tools/sorting/resources/Sorting_box.png",
    "sorting_table_frame": "../../tools/sorting/resources/Table_frame.png",
    "sorting_venn_base": "../../tools/sorting/resources/Venn_Base.png",
    "sorting_venn_diagram2_highlights_venn_diagram_2_highlight_centre": "../../tools/sorting/resources/Venn_diagram2_highlights/Venn_diagram_2_highlight_Centre.png",
    "sorting_venn_diagram2_highlights_venn_diagram_2_highlight_left": "../../tools/sorting/resources/Venn_diagram2_highlights/Venn_diagram_2_highlight_left.png",
    "sorting_venn_diagram2_highlights_venn_diagram_2_highlight_right": "../../tools/sorting/resources/Venn_diagram2_highlights/Venn_diagram_2_highlight_Right.png",
    "sorting_venn_diagram3_higlights_venn_highlight_bottom": "../../tools/sorting/resources/Venn_diagram3_higlights/Venn_Highlight_Bottom.png",
    "sorting_venn_diagram3_higlights_venn_highlight_centre": "../../tools/sorting/resources/Venn_diagram3_higlights/Venn_Highlight_Centre.png",
    "sorting_venn_diagram3_higlights_venn_highlight_left": "../../tools/sorting/resources/Venn_diagram3_higlights/Venn_Highlight_Left.png",
    "sorting_venn_diagram3_higlights_venn_highlight_right": "../../tools/sorting/resources/Venn_diagram3_higlights/Venn_Highlight_Right.png",
    "sorting_venn_diagram3_higlights_venn_highlight_top": "../../tools/sorting/resources/Venn_diagram3_higlights/Venn_Highlight_Top.png",
    "sorting_venn_diagram3_higlights_venn_highlight_top_left": "../../tools/sorting/resources/Venn_diagram3_higlights/Venn_Highlight_Top_Left.png",
    "sorting_venn_diagram3_higlights_venn_highlight_top_right": "../../tools/sorting/resources/Venn_diagram3_higlights/Venn_Highlight_Top_right.png",
    "sorting_venn_diagram_2": "../../tools/sorting/resources/Venn_diagram_2.png",
    "sorting_venn_diagram_3_colour": "../../tools/sorting/resources/Venn_diagram_3_colour.png"
};
// Cocos Preloaded Resources
var g_resources = [
    {src:window.bl.resources['images_closenormal']},
    {src:window.bl.resources['images_deep_water_background']},
    {src:window.bl.resources['images_object']},
    {src:window.bl.resources['images_sand_background']},
    {src:window.bl.resources['images_tooltip']},
    {src:window.bl.resources['clock_am']},
    {src:window.bl.resources['clock_am_small']},
    {src:window.bl.resources['clock_arrow_down']},
    {src:window.bl.resources['clock_arrow_down_small']},
    {src:window.bl.resources['clock_arrow_up']},
    {src:window.bl.resources['clock_arrow_up_small']},
    {src:window.bl.resources['clock_clock_cards_clock_card_1']},
    {src:window.bl.resources['clock_clock_cards_clock_card_10']},
    {src:window.bl.resources['clock_clock_cards_clock_card_11']},
    {src:window.bl.resources['clock_clock_cards_clock_card_12']},
    {src:window.bl.resources['clock_clock_cards_clock_card_2']},
    {src:window.bl.resources['clock_clock_cards_clock_card_3']},
    {src:window.bl.resources['clock_clock_cards_clock_card_4']},
    {src:window.bl.resources['clock_clock_cards_clock_card_5']},
    {src:window.bl.resources['clock_clock_cards_clock_card_6']},
    {src:window.bl.resources['clock_clock_cards_clock_card_7']},
    {src:window.bl.resources['clock_clock_cards_clock_card_8']},
    {src:window.bl.resources['clock_clock_cards_clock_card_9']},
    {src:window.bl.resources['clock_clock_centre_pin']},
    {src:window.bl.resources['clock_clock_face']},
    {src:window.bl.resources['clock_clock_numbers_3_6_9_12']},
    {src:window.bl.resources['clock_clock_numbers_all']},
    {src:window.bl.resources['clock_digital_bg']},
    {src:window.bl.resources['clock_digital_bg_small']},
    {src:window.bl.resources['clock_digits_0']},
    {src:window.bl.resources['clock_digits_0_small']},
    {src:window.bl.resources['clock_digits_1']},
    {src:window.bl.resources['clock_digits_1_small']},
    {src:window.bl.resources['clock_digits_2']},
    {src:window.bl.resources['clock_digits_2_small']},
    {src:window.bl.resources['clock_digits_3']},
    {src:window.bl.resources['clock_digits_3_small']},
    {src:window.bl.resources['clock_digits_4']},
    {src:window.bl.resources['clock_digits_4_small']},
    {src:window.bl.resources['clock_digits_5']},
    {src:window.bl.resources['clock_digits_5_small']},
    {src:window.bl.resources['clock_digits_6']},
    {src:window.bl.resources['clock_digits_6_small']},
    {src:window.bl.resources['clock_digits_7']},
    {src:window.bl.resources['clock_digits_7_small']},
    {src:window.bl.resources['clock_digits_8']},
    {src:window.bl.resources['clock_digits_8_small']},
    {src:window.bl.resources['clock_digits_9']},
    {src:window.bl.resources['clock_digits_9_small']},
    {src:window.bl.resources['clock_digits_colon']},
    {src:window.bl.resources['clock_digits_colon_small']},
    {src:window.bl.resources['clock_hour_hand']},
    {src:window.bl.resources['clock_hour_hand_handle']},
    {src:window.bl.resources['clock_minute_hand']},
    {src:window.bl.resources['clock_minute_hand_handle']},
    {src:window.bl.resources['clock_options_close_button']},
    {src:window.bl.resources['clock_options_digital_button_grey']},
    {src:window.bl.resources['clock_options_digital_button_orange']},
    {src:window.bl.resources['clock_options_hour_button_grey']},
    {src:window.bl.resources['clock_options_hour_button_orange']},
    {src:window.bl.resources['clock_options_minute_button_grey']},
    {src:window.bl.resources['clock_options_minute_button_orange']},
    {src:window.bl.resources['clock_options_open_button']},
    {src:window.bl.resources['clock_options_panel']},
    {src:window.bl.resources['clock_options_sentence_button_grey']},
    {src:window.bl.resources['clock_options_sentence_button_orange']},
    {src:window.bl.resources['clock_options_words_button_grey']},
    {src:window.bl.resources['clock_options_words_button_orange']},
    {src:window.bl.resources['clock_pm']},
    {src:window.bl.resources['clock_pm_small']},
    {src:window.bl.resources['clock_settings_12hr_off']},
    {src:window.bl.resources['clock_settings_12hr_on']},
    {src:window.bl.resources['clock_settings_24hr_off']},
    {src:window.bl.resources['clock_settings_24hr_on']},
    {src:window.bl.resources['clock_settings_analog_button_off']},
    {src:window.bl.resources['clock_settings_analog_button_on']},
    {src:window.bl.resources['clock_settings_analoganddigital_button_off']},
    {src:window.bl.resources['clock_settings_analoganddigital_button_on']},
    {src:window.bl.resources['clock_settings_digital_button_off']},
    {src:window.bl.resources['clock_settings_digital_button_on']},
    {src:window.bl.resources['clock_settings_free_form_bg']},
    {src:window.bl.resources['clock_settings_free_form_closebutton']},
    {src:window.bl.resources['clock_settings_markers_off']},
    {src:window.bl.resources['clock_settings_markers_on']},
    {src:window.bl.resources['clock_settings_numbers_off']},
    {src:window.bl.resources['clock_settings_numbers_on']},
    {src:window.bl.resources['clock_settings_sentence_off']},
    {src:window.bl.resources['clock_settings_sentence_on']},
    {src:window.bl.resources['clock_settings_settings_button']},
    {src:window.bl.resources['clock_settings_settings_button_base']},
    {src:window.bl.resources['clock_settings_words_off']},
    {src:window.bl.resources['clock_settings_words_on']},
    {src:window.bl.resources['clock_title']},
    {src:window.bl.resources['geoboard_addpinbutton']},
    {src:window.bl.resources['geoboard_anglebackground']},
    {src:window.bl.resources['geoboard_arrow_down_button']},
    {src:window.bl.resources['geoboard_arrow_up_button']},
    {src:window.bl.resources['geoboard_background']},
    {src:window.bl.resources['geoboard_band_1_white']},
    {src:window.bl.resources['geoboard_band_button']},
    {src:window.bl.resources['geoboard_band_button_base']},
    {src:window.bl.resources['geoboard_band_circle']},
    {src:window.bl.resources['geoboard_bandbutton']},
    {src:window.bl.resources['geoboard_bandpart']},
    {src:window.bl.resources['geoboard_centrepinbutton']},
    {src:window.bl.resources['geoboard_centrepoint_button']},
    {src:window.bl.resources['geoboard_circlepin_button']},
    {src:window.bl.resources['geoboard_circlepin_button_base']},
    {src:window.bl.resources['geoboard_circularbutton']},
    {src:window.bl.resources['geoboard_colour_box_empty']},
    {src:window.bl.resources['geoboard_colour_select']},
    {src:window.bl.resources['geoboard_colour_selected']},
    {src:window.bl.resources['geoboard_geoboard_title']},
    {src:window.bl.resources['geoboard_hand']},
    {src:window.bl.resources['geoboard_hand_up']},
    {src:window.bl.resources['geoboard_info_side_button']},
    {src:window.bl.resources['geoboard_info_side_button_highlight']},
    {src:window.bl.resources['geoboard_inspect_button']},
    {src:window.bl.resources['geoboard_isopin_button']},
    {src:window.bl.resources['geoboard_isopin_button_base']},
    {src:window.bl.resources['geoboard_label_panel']},
    {src:window.bl.resources['geoboard_minuspinbutton']},
    {src:window.bl.resources['geoboard_newbandbutton']},
    {src:window.bl.resources['geoboard_number_box']},
    {src:window.bl.resources['geoboard_parallelsidearrow']},
    {src:window.bl.resources['geoboard_pin']},
    {src:window.bl.resources['geoboard_pin_white']},
    {src:window.bl.resources['geoboard_pin_white_noshadow']},
    {src:window.bl.resources['geoboard_pinboardbackground']},
    {src:window.bl.resources['geoboard_propertybackground']},
    {src:window.bl.resources['geoboard_removebandbutton']},
    {src:window.bl.resources['geoboard_rubberband_base']},
    {src:window.bl.resources['geoboard_rubberband_icon']},
    {src:window.bl.resources['geoboard_sameanglebutton']},
    {src:window.bl.resources['geoboard_sameanglebuttonselected']},
    {src:window.bl.resources['geoboard_samesidelengthbutton']},
    {src:window.bl.resources['geoboard_samesidelengthbuttonselected']},
    {src:window.bl.resources['geoboard_samesidelengthnotch']},
    {src:window.bl.resources['geoboard_showanglesbutton']},
    {src:window.bl.resources['geoboard_showanglesbuttonselected']},
    {src:window.bl.resources['geoboard_showparallelsidesbutton']},
    {src:window.bl.resources['geoboard_showparallelsidesbuttonselected']},
    {src:window.bl.resources['geoboard_showsidelengthsbutton']},
    {src:window.bl.resources['geoboard_showsidelengthsbuttonselected']},
    {src:window.bl.resources['geoboard_sidelabelbackground']},
    {src:window.bl.resources['geoboard_singlebandpart']},
    {src:window.bl.resources['geoboard_squarelatticebutton']},
    {src:window.bl.resources['geoboard_squarepin_button']},
    {src:window.bl.resources['geoboard_squarepin_button_base']},
    {src:window.bl.resources['geoboard_trash_button']},
    {src:window.bl.resources['geoboard_trash_button_base']},
    {src:window.bl.resources['geoboard_triangularlatticebutton']},
    {src:window.bl.resources['geoboard_whitepin']},
    {src:window.bl.resources['longdivision_bar_slither_white']},
    {src:window.bl.resources['longdivision_bar_slither_white_left']},
    {src:window.bl.resources['longdivision_bar_slither_white_right']},
    {src:window.bl.resources['longdivision_barsbox']},
    {src:window.bl.resources['longdivision_clear_button']},
    {src:window.bl.resources['longdivision_decimalpoint']},
    {src:window.bl.resources['longdivision_digitchangehitzone']},
    {src:window.bl.resources['longdivision_labels_label_1']},
    {src:window.bl.resources['longdivision_labels_label_10+1']},
    {src:window.bl.resources['longdivision_labels_label_10+2']},
    {src:window.bl.resources['longdivision_labels_label_10+3']},
    {src:window.bl.resources['longdivision_labels_label_10+4']},
    {src:window.bl.resources['longdivision_labels_label_10_1']},
    {src:window.bl.resources['longdivision_labels_label_10_2']},
    {src:window.bl.resources['longdivision_labels_label_10_3']},
    {src:window.bl.resources['longdivision_labels_label_10']},
    {src:window.bl.resources['longdivision_labels_label_100']},
    {src:window.bl.resources['longdivision_labels_label_1000']},
    {src:window.bl.resources['longdivision_labels_label_1over10']},
    {src:window.bl.resources['longdivision_labels_label_1over100']},
    {src:window.bl.resources['longdivision_labels_label_1over1000']},
    {src:window.bl.resources['longdivision_labels_label_hundreds']},
    {src:window.bl.resources['longdivision_labels_label_hundredths']},
    {src:window.bl.resources['longdivision_labels_label_number10']},
    {src:window.bl.resources['longdivision_labels_label_tens']},
    {src:window.bl.resources['longdivision_labels_label_tenths']},
    {src:window.bl.resources['longdivision_labels_label_thousands']},
    {src:window.bl.resources['longdivision_labels_label_thousandths']},
    {src:window.bl.resources['longdivision_labels_label_units']},
    {src:window.bl.resources['longdivision_magnifyingglass']},
    {src:window.bl.resources['longdivision_number_wheel_numberwheelsectionbackground']},
    {src:window.bl.resources['longdivision_number_wheel_nw_1_ov']},
    {src:window.bl.resources['longdivision_number_wheel_nw_2_ov']},
    {src:window.bl.resources['longdivision_number_wheel_nw_3_ov']},
    {src:window.bl.resources['longdivision_number_wheel_nw_4_ov']},
    {src:window.bl.resources['longdivision_number_wheel_nw_5_ov']},
    {src:window.bl.resources['longdivision_number_wheel_nw_6_ov']},
    {src:window.bl.resources['longdivision_numberbox']},
    {src:window.bl.resources['longdivision_numberpicker_box']},
    {src:window.bl.resources['longdivision_numberpicker_down_arrow']},
    {src:window.bl.resources['longdivision_numberpicker_left_arrow']},
    {src:window.bl.resources['longdivision_numberpicker_number_bg']},
    {src:window.bl.resources['longdivision_numberpicker_right_arrow']},
    {src:window.bl.resources['longdivision_numberpicker_up_arrow']},
    {src:window.bl.resources['longdivision_numberpickerbox']},
    {src:window.bl.resources['longdivision_numberwheel_down_arrow']},
    {src:window.bl.resources['longdivision_numberwheel_up_arrow']},
    {src:window.bl.resources['longdivision_question_tray']},
    {src:window.bl.resources['longdivision_reset_button']},
    {src:window.bl.resources['longdivision_settings_free_form_closebutton']},
    {src:window.bl.resources['longdivision_settings_label_off']},
    {src:window.bl.resources['longdivision_settings_label_on']},
    {src:window.bl.resources['longdivision_settings_long_div_settings_bg']},
    {src:window.bl.resources['longdivision_settings_numbers_off']},
    {src:window.bl.resources['longdivision_settings_numbers_on']},
    {src:window.bl.resources['longdivision_settings_powers_off']},
    {src:window.bl.resources['longdivision_settings_powers_on']},
    {src:window.bl.resources['longdivision_settings_settings_button']},
    {src:window.bl.resources['longdivision_settings_settings_button_base']},
    {src:window.bl.resources['longdivision_settings_table_off']},
    {src:window.bl.resources['longdivision_settings_table_on']},
    {src:window.bl.resources['longdivision_single_white_pixel']},
    {src:window.bl.resources['longdivision_table_=']},
    {src:window.bl.resources['longdivision_table_answerbox']},
    {src:window.bl.resources['longdivision_table_box']},
    {src:window.bl.resources['longdivision_table_down_arrow']},
    {src:window.bl.resources['longdivision_table_sectionbox']},
    {src:window.bl.resources['longdivision_table_up_arrow']},
    {src:window.bl.resources['longdivision_table_x']},
    {src:window.bl.resources['longdivision_testbigwhitebox']},
    {src:window.bl.resources['longdivision_title_longdivision']},
    {src:window.bl.resources['sorting_barchart_axis_x']},
    {src:window.bl.resources['sorting_barchart_axis_y']},
    {src:window.bl.resources['sorting_barchart_base']},
    {src:window.bl.resources['sorting_bars_blue_bar_1']},
    {src:window.bl.resources['sorting_bars_blue_bar_2']},
    {src:window.bl.resources['sorting_bars_blue_bar_3']},
    {src:window.bl.resources['sorting_bars_blue_bar_4']},
    {src:window.bl.resources['sorting_bars_blue_bar_5']},
    {src:window.bl.resources['sorting_bars_green_bar_1']},
    {src:window.bl.resources['sorting_bars_green_bar_2']},
    {src:window.bl.resources['sorting_bars_green_bar_3']},
    {src:window.bl.resources['sorting_bars_green_bar_4']},
    {src:window.bl.resources['sorting_bars_green_bar_5']},
    {src:window.bl.resources['sorting_bars_orange_bar_1']},
    {src:window.bl.resources['sorting_bars_orange_bar_2']},
    {src:window.bl.resources['sorting_bars_orange_bar_3']},
    {src:window.bl.resources['sorting_bars_orange_bar_4']},
    {src:window.bl.resources['sorting_bars_orange_bar_5']},
    {src:window.bl.resources['sorting_bars_pink_bar_1']},
    {src:window.bl.resources['sorting_bars_pink_bar_2']},
    {src:window.bl.resources['sorting_bars_pink_bar_3']},
    {src:window.bl.resources['sorting_bars_pink_bar_4']},
    {src:window.bl.resources['sorting_bars_pink_bar_5']},
    {src:window.bl.resources['sorting_bars_red_bar_1']},
    {src:window.bl.resources['sorting_bars_red_bar_2']},
    {src:window.bl.resources['sorting_bars_red_bar_3']},
    {src:window.bl.resources['sorting_bars_red_bar_4']},
    {src:window.bl.resources['sorting_bars_red_bar_5']},
    {src:window.bl.resources['sorting_cards_blank_card']},
    {src:window.bl.resources['sorting_cards_character_card_assets_eyes_1']},
    {src:window.bl.resources['sorting_cards_character_card_assets_eyes_2']},
    {src:window.bl.resources['sorting_cards_character_card_assets_eyes_3']},
    {src:window.bl.resources['sorting_cards_character_card_assets_horns']},
    {src:window.bl.resources['sorting_cards_character_card_assets_mask_legs_2']},
    {src:window.bl.resources['sorting_cards_character_card_assets_mask_legs_3']},
    {src:window.bl.resources['sorting_cards_character_card_assets_mask_legs_4']},
    {src:window.bl.resources['sorting_cards_giraffe_card']},
    {src:window.bl.resources['sorting_cards_lion_card']},
    {src:window.bl.resources['sorting_cards_mouse_card']},
    {src:window.bl.resources['sorting_cards_pig_card']},
    {src:window.bl.resources['sorting_cards_rabbit_card']},
    {src:window.bl.resources['sorting_cards_scorpion_card']},
    {src:window.bl.resources['sorting_dock']},
    {src:window.bl.resources['sorting_key_table']},
    {src:window.bl.resources['sorting_shapes_equilateral_blue_1']},
    {src:window.bl.resources['sorting_shapes_equilateral_green_1']},
    {src:window.bl.resources['sorting_shapes_equilateral_red_1']},
    {src:window.bl.resources['sorting_shapes_equilateral_white_1']},
    {src:window.bl.resources['sorting_shapes_equilateral_yellow_1']},
    {src:window.bl.resources['sorting_shapes_hexagon_white_1']},
    {src:window.bl.resources['sorting_shapes_isosceles_blue_1']},
    {src:window.bl.resources['sorting_shapes_isosceles_green_1']},
    {src:window.bl.resources['sorting_shapes_isosceles_red_1']},
    {src:window.bl.resources['sorting_shapes_isosceles_white_1']},
    {src:window.bl.resources['sorting_shapes_isosceles_yellow_1']},
    {src:window.bl.resources['sorting_shapes_octogun_white_1']},
    {src:window.bl.resources['sorting_shapes_pentagon_white_1']},
    {src:window.bl.resources['sorting_shapes_rectangle_red_1']},
    {src:window.bl.resources['sorting_shapes_scalene_blue_1']},
    {src:window.bl.resources['sorting_shapes_scalene_green_1']},
    {src:window.bl.resources['sorting_shapes_scalene_white_1']},
    {src:window.bl.resources['sorting_shapes_scalene_yellow_1']},
    {src:window.bl.resources['sorting_shapes_square_blue_1']},
    {src:window.bl.resources['sorting_shapes_square_green_1']},
    {src:window.bl.resources['sorting_shapes_square_red_1']},
    {src:window.bl.resources['sorting_shapes_square_white_1']},
    {src:window.bl.resources['sorting_shapes_square_yellow_1']},
    {src:window.bl.resources['sorting_sorting_box']},
    {src:window.bl.resources['sorting_table_frame']},
    {src:window.bl.resources['sorting_venn_base']},
    {src:window.bl.resources['sorting_venn_diagram2_highlights_venn_diagram_2_highlight_centre']},
    {src:window.bl.resources['sorting_venn_diagram2_highlights_venn_diagram_2_highlight_left']},
    {src:window.bl.resources['sorting_venn_diagram2_highlights_venn_diagram_2_highlight_right']},
    {src:window.bl.resources['sorting_venn_diagram3_higlights_venn_highlight_bottom']},
    {src:window.bl.resources['sorting_venn_diagram3_higlights_venn_highlight_centre']},
    {src:window.bl.resources['sorting_venn_diagram3_higlights_venn_highlight_left']},
    {src:window.bl.resources['sorting_venn_diagram3_higlights_venn_highlight_right']},
    {src:window.bl.resources['sorting_venn_diagram3_higlights_venn_highlight_top']},
    {src:window.bl.resources['sorting_venn_diagram3_higlights_venn_highlight_top_left']},
    {src:window.bl.resources['sorting_venn_diagram3_higlights_venn_highlight_top_right']},
    {src:window.bl.resources['sorting_venn_diagram_2']},
    {src:window.bl.resources['sorting_venn_diagram_3_colour']}
];
